id: P007068
initial_creation_type: ocr
source_metadata:
  id: bdr:W22433
  title: བདེ་མཆོག་ཆོས་འབྱུང
  author: ''
  volumes:
    3be7fffdda1c4df1b269533fabce0c5a:
      image_group_id: I1742
      title: ''
      volume_number: 1
      total_pages: 591
      base_file: v001.txt
ebook_metadata:
  title: བདེ་མཆོག་ཆོས་འབྱུང
  author: ''
  sku: P007068
  cover: cover.jpg
  layers:
  - pagination
