id: P007068
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:39:29.898252
source_metadata:
  id: bdr:W22433
  title: བདེ་མཆོག་ཆོས་འབྱུང
  author: ''
  volumes:
    3be7fffdda1c4df1b269533fabce0c5a:
      image_group_id: I1742
      title: ''
      volume_number: 1
      total_pages: 591
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
