id: IF26A9AED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T18:39:13+00:00'
last_modified: '2022-06-09T04:31:36.307697+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22433
  title: བདེ་མཆོག་ཆོས་འབྱུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2972':
      image_group_id: I1742
      title: ''
      total_pages: 591
      order: 1
      base_file: 2972.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
